name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Create directory on Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.237.252.79 "mkdir -p /home/ubuntu/seranyaAPI"

      - name: Copy files to Lightsail
        run: |
          scp -o StrictHostKeyChecking=no -r * ubuntu@15.237.252.79:/home/ubuntu/seranyaAPI/

      - name: SSH into Lightsail and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.237.252.79 <<EOF
          cd /home/ubuntu/seranyaAPI
          sudo docker build -t seranya-api .
          sudo docker stop seranya-api || true
          sudo docker rm seranya-api || true
          sudo docker run -d -p 5000:5000 --name seranya-api seranya-api
          EOF